#!/bin/sh
set -e

changed_files=$(git diff --name-only ORIG_HEAD HEAD)

check_run() {
    pattern=$1
    cmd=$2
    msg=$3

    if echo "$changed_files" | grep -qE "$pattern"; then
        echo "--- [Husky] $msg ---"
        eval "$cmd"
    fi
}

check_run "package(-lock)?\.json" "npm install" "Alteração de dependências: Instalando..."
check_run "backend/prisma/schema\.prisma" "npm run prisma:generate" "Alteração no Schema: Gerando Prisma Client..."
check_run "^shared/" "npm run build:shared" "Alteração no pacote shared: Recompilando..."
